const barcodeCountryRanges: { start: number; end: number; country: string }[] =
  [
    { start: 0, end: 9, country: "Mostly United States but could be Canada" },
    { start: 10, end: 19, country: "Mostly Canada but could be United States" },
    { start: 20, end: 29, country: "Restricted distribution" },
    { start: 30, end: 39, country: "United States drugs (National Drug Code)" },
    {
      start: 40,
      end: 49,
      country: "Used for restricted circulation within a region",
    },
    { start: 50, end: 59, country: "Reserved for future use" },
    { start: 60, end: 99, country: "United States and Canada" },
    { start: 100, end: 139, country: "United States" },
    { start: 200, end: 299, country: "Restricted distribution" },
    { start: 300, end: 379, country: "France and Monaco" },
    { start: 380, end: 380, country: "Bulgaria" },
    { start: 383, end: 383, country: "Slovenia" },
    { start: 385, end: 385, country: "Croatia" },
    { start: 387, end: 387, country: "Bosnia and Herzegovina" },
    { start: 389, end: 389, country: "Montenegro" },
    { start: 400, end: 440, country: "Germany" },
    { start: 450, end: 459, country: "Japan" },
    { start: 460, end: 469, country: "Russia" },
    { start: 470, end: 470, country: "Kyrgyzstan" },
    { start: 471, end: 471, country: "Taiwan" },
    { start: 474, end: 474, country: "Estonia" },
    { start: 475, end: 475, country: "Latvia" },
    { start: 476, end: 476, country: "Azerbaijan" },
    { start: 477, end: 477, country: "Lithuania" },
    { start: 478, end: 478, country: "Uzbekistan" },
    { start: 479, end: 479, country: "Sri Lanka" },
    { start: 480, end: 480, country: "Philippines" },
    { start: 481, end: 481, country: "Belarus" },
    { start: 482, end: 482, country: "Ukraine" },
    { start: 484, end: 484, country: "Moldova" },
    { start: 485, end: 485, country: "Armenia" },
    { start: 486, end: 486, country: "Georgia" },
    { start: 487, end: 487, country: "Kazakhstan" },
    { start: 488, end: 488, country: "Tajikistan" },
    { start: 489, end: 489, country: "Hong Kong" },
    { start: 490, end: 499, country: "Japan" },
    { start: 500, end: 509, country: "United Kingdom" },
    { start: 520, end: 521, country: "Greece" },
    { start: 528, end: 528, country: "Lebanon" },
    { start: 529, end: 529, country: "Cyprus" },
    { start: 530, end: 530, country: "Albania" },
    { start: 535, end: 535, country: "Malta" },
    { start: 539, end: 539, country: "Ireland" },
    { start: 540, end: 549, country: "Belgium and Luxembourg" },
    { start: 560, end: 560, country: "Portugal" },
    { start: 569, end: 569, country: "Iceland" },
    { start: 570, end: 579, country: "Denmark, Faroe Islands and Greenland" },
    { start: 590, end: 590, country: "Poland" },
    { start: 594, end: 594, country: "Romania" },
    { start: 599, end: 599, country: "Hungary" },
    { start: 690, end: 699, country: "China" },
    { start: 700, end: 709, country: "Norway" },
    { start: 729, end: 729, country: "Israel" },
    { start: 730, end: 739, country: "Sweden" },
    { start: 750, end: 750, country: "Mexico" },
    { start: 754, end: 755, country: "Canada" },
    { start: 760, end: 769, country: "Switzerland and Liechtenstein" },
    { start: 770, end: 771, country: "Colombia" },
    { start: 789, end: 790, country: "Brazil" },
    { start: 800, end: 839, country: "Italy, San Marino and Vatican City" },
    { start: 840, end: 849, country: "Spain and Andorra" },
    { start: 900, end: 919, country: "Austria" },
    { start: 930, end: 939, country: "Australia" },
    { start: 940, end: 949, country: "New Zealand" },
    { start: 955, end: 955, country: "Malaysia" },
    { start: 958, end: 958, country: "Macau" },
  ];

export const getCountryFromBarcode = (barcode: string): string => {
  if (barcode.length < 3) return "Invalid barcode";

  const prefix = parseInt(barcode.substring(0, 3), 10);
  const match = barcodeCountryRanges.find(
    ({ start, end }) => prefix >= start && prefix <= end,
  );

  return match ? match.country : "Unknown country";
};
